### ISSUE TITLE
Error opening yxdb file

### ISSUE THREAD

**Issue by Siva-2018** [tlarsendataguy-yxdb/yxdb-odbc#1]
Hi Tom,
I am trying to open a YXDB file that got generated in Alteryx version 2023.1.1.200.
I repeatedly keep getting the following error. I tried the same code with the test yxdb files that are there in your repository and it worked without trouble. Would you know what could be the issue?
Thanks,

File "d:\Macro_Dev\m1_leveshtein_distance\leveshtein_distance.py", line 11, in <module>
    ydb = YxdbReader(path="test1.yxdb")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Macro_Dev\m1_leveshtein_distance\Lib\site-packages\yxdb\yxdb_reader.py", line 61, in __init__
    raise Exception(invalid_yxdb_msg)
Exception: file is not a valid YXDB format

**Comment by tlarsendataguy** [comment]
Was the YXDB file generated by the AMP engine?

When Alteryx released the AMP engine, they also changed the YXDB format. My YXDB reader packages are only compatible with the older YXDB format. You can either turn off the AMP engine, or select the option "AMP Only: Compatible with 18.1 and Earlier" in the output tool.

So far, Alteryx has not released the file spec for AMP-generated YXDB files. Once (if) they do, my plan is to update these reader packages to be compatible.

**Comment by Siva-2018** [comment]
Great, thanks Tom,
Disabled AMP and it worked.
Cheers,
Siva
